"""Add email field to users table

Revision ID: ecd2cc2e9e99
Revises:
Create Date: 2026-02-15 00:51:51.523142

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ecd2cc2e9e99"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(length=255), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "email_verified",
            sa.Boolean(),
            nullable=True,
            server_default=sa.text("false"),
        ),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    # 更新现有行，将email_verified设置为False
    # 对于SQLite和PostgreSQL都适用
    op.execute("UPDATE users SET email_verified = false WHERE email_verified IS NULL")

    # 如果需要，将列改为非空（但现有用户没有邮箱，所以暂时保持可为空）
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_column("users", "email_verified")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
